public enum Symbol {
  ID, NUMBER, PLUS, MINUS, GREATER, GREATER_E, LESS, LESS_E, EQUAL, DIFF, MULT, DIV, MOD, LEFT_P, RIGHT_P, LEFT_B,
  RIGHT_B, COMMA, SEMICOLON, NOT, IF, ELSE, FOR, IN, RANGE, PRINT, PRINTLN, WHILE, EOF, ASSIGN, AND, OR, VAR, INT
}